SymEdit\Bundle\BlogBundle\Model\Category:
    type: mappedSuperclass
    table: category
    gedmo:
        tree:
            type: materializedPath
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            gedmo:
                - treePathSource
        title:
            type: string
            length: 255
        level:
            type: integer
            nullable: true
            gedmo:
                - treeLevel
        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                treePath:
                    appendId: false
                    separator: "/"
                    endsWithSeparator: false
        seo:
            type: json_array
            nullable: true
    manyToOne:
        parent:
            targetEntity: SymEdit\Bundle\BlogBundle\Model\Category
            inversedBy: children
            joinColumns:
                parent:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: SymEdit\Bundle\BlogBundle\Model\Category
            cascade:
                - remove
                - persist
            mappedBy: parent
    manyToMany:
        posts:
            targetEntity: SymEdit\Bundle\BlogBundle\Model\PostInterface
            mappedBy: categories
            orderBy:
                createdAt: DESC
